version: "3.8"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    ports:
      - "5432:5432"
    command: >
      postgres
        -c log_destination=stderr
        -c logging_collector=on
        -c log_directory="/var/log/postgresql"

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: